### ISSUE TITLE
Preferred way to tackle type issues

### ISSUE THREAD

**Issue by mvdve** [postalsys/imapflow#105]
There are some issues with the type declarations for this module, a couple of examples:

- There is a types declaration within the module, and there is @types/imapflow
- The internal type declarations are not loaded and need to be included manually.
- @types/imapflow and the internal types file declare different types
- Within both type definitions there are issues. For example
    - types.d.ts declares fetch with a return type of void
    - types.d.ts declares download with a return type of ReadableStream where @types/imapflow declares Readable within the returned promise.
    - @types/imapflow declares MessageStructureObject.parameters and MessageStructureObject.dispositionParameters as string instead of any.

#82 is for example caused by loading @types/imapflow.

What is the preferred path to handle the types within this module? I would like to help but not sure if i need to PR this module of @types/imapflow.

**Comment by andris9** [comment]
It's kind of complicated. I added those built-in types not because I needed those but because it was easy to autogenerate types from the JSDoc comments. Later it turned out that these autogenerated types caused more issues than helped. People started complaining that things did not work, and I removed the link to the types file. I have nothing to do with _@types/imapflow_.

In general, ImapFlow is built to manage lower-level IMAP handling for [EmailEngine](https://emailengine.app/). I don't use typescript for either of these projects. So if you're interested in getting correct types, I suggest you team up with whoever is behind _@types/imapflow_ and get those fixed/updated. The built-in types are autogenerated from JSDoc for each new release, so there is no point in modifying these (any change will be overwritten).
