### ISSUE TITLE
Failure to receive some emails in the Gmail inbox

### ISSUE THREAD

**Issue by hossein-hypadrive** [postalsys/imapflow#199]
**Describe the bug**
Although I can see all the emails in the Gmail inbox in the browser, but when I connect with Imapflow, I can't get some of them.

**Comment by andris9** [comment]
You would have to check the logs. Are these emails even listed in the message listing output?

**Comment by milad-ahmd** [comment]
I have the same issue to fetch emails from a Gmail account configured with an app password. The problem is that the email fetching is inconsistent: we seem to only retrieve every other email. For instance, we might receive the 1st, 3rd, and 5th emails, and miss the 2nd, 4th, etc. At other times, this pattern reverses, and we miss the 1st, 3rd, etc., while receiving the 2nd, 4th, and so on. @andris9
