### ISSUE TITLE
How to delete messages By UID?

### ISSUE THREAD

**Issue by killghost** [postalsys/imapflow#206]
for await (let message of client.fetch('1:*', { envelope: true, uid: true })) {
                console.log(`${message.uid}: ${message.envelope.subject}`);

                if (message.uid==245507)
                {
                    messages.push(message);
                    try {
                        await client.messageDelete("245507", {uid: true})
                        //await client.messageDelete('100', { uid: true });
                    } catch (error) {
                        console.log(error);
                    }
                    
                    break;
                }               
            }
            
            
          
Can I Use messageDelete to Delete Email?

**Comment by Remscar** [comment]
I've been also trying to move messages by UID and it doesn't seem to work too.

**Comment by andris9** [comment]
@Remscar Yes, you are correct. However, the issue is not the `trySend` method but the fact that there is only a single TCP connection, and all IMAP commands must be sent serially. As ImapFlow is still processing the FETCH command inside the async generator loop, any additional command will be queued for processing _after_ FETCH. But _FETCH_ can not be completed due to the await waiting until the issued command inside the loop is completed, and you end up in a deadlock.

**Comment by Remscar** [comment]
> @Remscar Yes, you are correct. However, the issue is not the `trySend` method but the fact that there is only a single TCP connection, and all IMAP commands must be sent serially. As ImapFlow is still processing the FETCH command inside the async generator loop, any additional command will be queued for processing _after_ FETCH. But _FETCH_ can not be completed due to the await waiting until the issued command inside the loop is completed, and you end up in a deadlock.

That's some really great context, didn't know about the IMAP serial command requirement, thanks for the explanation!
