### ISSUE TITLE
Mailbox doesn't exist: INBOX.SENT

### ISSUE THREAD

**Issue by adobeusstokyocom** [postalsys/imapflow#78]
Hello.

I am writing the following code to save the message in SENT box.

`await imapClient.append("SENT", "Hello world")`

But I am receiving the following error:

`Mailbox doesn't exist: INBOX.SENT`

Any help is highly appreciated.
Thank you.

**Comment by andris9** [comment]
ImapFlow prefixes mailbox path because the server indicates that INBOX is the required namespace.

Could you run the following code snippet against your email account and send me the output logs. ImapFlow does not log passwords, but you can remove anything you do not want to disclose. I'm mostly interested in the output for ID, NAMESPACE, CAPABILITY responses, and also the LIST response for the SENT folder.

```js
const { ImapFlow } = require('imapflow');
const client = new ImapFlow({
    host: 'HOSTNAME',
    port: 993,
    secure: true,
    auth: {
        user: 'USERNAME',
        pass: 'PASSWORD'
    }
});

const main = async () => {
    await client.connect();
    await client.list();
    await client.logout();
};

main().catch(err => console.error(err));
```

**Comment by adobeusstokyocom** [comment]
@andris9 Thank you for your quick reply. I did as you said. And it showed me "INBOX.Sent". So I changed my code to:

`await imapClient.append("Sent", "Hello world")`

I think the problem was in uppercase. But it worked fine now.

Thank you so much again.

**Comment by andris9** [comment]
OK. Only INBOX is case insensitive in IMAP, everything else is case sensitive

**Comment by adobeusstokyocom** [comment]
Got it. Thanks.
