### ISSUE TITLE
since on search option doesn't work

### ISSUE THREAD

**Issue by rounsmith** [postalsys/imapflow#88]
Hello , 

I tried to use the imapflow with search function and it doesn't seem to work as intented.

I am using the following 

`await client.connect();
  let lock = await client.getMailboxLock('INBOX');

  let date = new Date(new Date().setMinutes(new Date().getMinutes() - 5));
  console.log(date);
  try {
   for await (let mesg of client.fetch(
      {
        from: 'noreply@gmail.com',
        since: date,
      },
      { envelope: true, internalDate: true, source: true }
    )) {
      console.log(mesg);
    }
  } catch (error) {
    console.log(error);
  } finally {
    // Make sure lock is released, otherwise next `getMailboxLock()` never returns
    lock.release();
  }`

I am trying to fetch the mail that were sent from the email the past 5 minutes. Instead it fetchs all the emails from today instead of today last 5 minutes.

In your documentation it's not clear if it compares with date+time and only time but it only says this 

since | Date           \|             string | <optional> | Matches messages received after date
-- | -- | -- | --

. In sentOn search option it says that it ignores time but on since option.

So since search option ignores time as well?

**Comment by andris9** [comment]
IMAP search is day based, you can’t search by hour or minute.

**Comment by rounsmith** [comment]
Could it be written on documentation so it's not as confusing as it is now? I could also correct the docs if  you like.

**Comment by andris9** [comment]
Well, this is an IMAP limitation, not ImapFlow, as ImapFlow sends whatever you provide it to the server, but the server will ignore anything after the date part. So if you use `2022-10-10T06:34:06.364Z` in the search, the server will read it as `2022-10-10`. You can't even provide a timezone, there's no way to know how the server even processes that date part, is it UTC or the local date, where the server is hosted? There is absolutely nothing ImapFlow can do to fix or improve it 🤷‍♂️ If you like, you could improve the docs so that people who do not know so much about IMAP would understand it better.
